version: '3'
services:
  linebot:
    container_name: linebot
    build:
      context: .
      dockerfile: ./dockerfile
    env_file:
      - .env
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000